apiVersion: v1
kind: Service
metadata:
  labels:
    app: namenode
    app.kubernetes.io/managed-by: Helm
  name: namenode
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: namenode
  type: NodePort
status:
  loadBalancer: {}

